name: CI

on:
  push:
    branches:
      - '*'

jobs:
  ci:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings -A clippy::await_holding_lock

# @TODO: allocate github runner to execute tests
#      - name: Test
#        run: |
#          cargo check
#          cargo test --all

      - name: Build
        run: |
          cargo build --release
