name: CI

on:
  push:
    branches:
      - '*'

jobs:
  ci:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings -A clippy::await_holding_lock

# @TODO: allocate github runner to execute tests
#      - name: Test
#        run: |
#          cargo check
#          cargo test --all

      - name: Build
        run: |
          cargo build --release
